sudo: required

services:
  - docker

before_install:
  - docker build --build-arg GIT_BRANCH=${TRAVIS_BRANCH} --build-arg GIT_HASH=${TRAVIS_COMMIT} --tag example .
  - docker images

script:
  - docker run --rm=true example 